from typing import overload, Callable, Dict, Any

from .port import Port

# from ..meta.node import key_conf
# If you updated key_conf, don't forget here.

class Node:
    __abstract__: bool
    __entry__: staticmethod  # Callable[..., Any]
    __mappings__: Dict[str, Port]
    # mappers with role is ABSOLUTELY private attribute.

    """
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, node: Node) -> None: ...
    @overload
    def __init__(self, **inputs: Dict[str, Any]) -> None: ...
    def __init__(self, *args, **kwds) -> None: ...
    @overload
    def __call__(self) -> Any: ...
    @overload
    def __call__(self, **inputs: Dict[str, Any]) -> Any: ...
    def __call__(self, *args: Any, **kwds: Any) -> Any: ...
    """
    def __getattribute__(self, __name: str) -> Any: ...
    def __setattr__(self, __name: str, __value: Any) -> None: ...
    """
    # Reserved: oprater
    def __rshift__(self, node: Node) -> Any: ...
    def __rrshift__(self, node: Node) -> Any: ...
    """
